### PR TITLE
feat(jsdocs): `collapse` prop

### PR DESCRIPTION
**Pull request by cpreston321**
### 🔗 Linked issue

#14 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [X] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Resolves: #14

### 📝 Checklist

- [X] I have linked an issue or discussion.
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by cpreston321** [comment]
Thoughts? 

- How to set which group to default to `<details open>`?
- Should we default to first group to default to open?

**Comment by uncenter** [comment]
> How to set which group to default to `<details open>`?
How about `expanded="group1 group2"` or `opened="group1 group2"`?

**Comment by cpreston321** [comment]
@uncenter I guess that would work but you set the group on the code level using a `@group utils` which makes it a little confusing / strange. I assume that works but github 'closes' by default then open is optional

**Comment by pi0** [comment]
(PR now has too many conflicts. let's wait little bit longer to see how this generator will be used first before implementing and track with #14)

**Pull request closed without merging**
